curl -O http://www.isogg.org/tree/ISOGG_HapgrpA.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpB.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpC.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpD.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpE.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpF.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpG.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpH.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpI.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpJ.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpK.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpL.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpM.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpN.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpO.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpP.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpQ.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpR.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpS.html
curl -O http://www.isogg.org/tree/ISOGG_HapgrpT.html
curl -O http://www.isogg.org/tree/ISOGG_YDNA_SNP_Index.html
