php readgroup.php <ISOGG_HapgrpA.html >A.txt
php readgroup.php <ISOGG_HapgrpB.html >B.txt
php readgroup.php <ISOGG_HapgrpC.html >C.txt
php readgroup.php <ISOGG_HapgrpD.html >D.txt
php readgroup.php <ISOGG_HapgrpE.html >E.txt
php readgroup.php <ISOGG_HapgrpF.html >F.txt
php readgroup.php <ISOGG_HapgrpG.html >G.txt
php readgroup.php <ISOGG_HapgrpH.html >H.txt
php readgroup.php <ISOGG_HapgrpI.html >I.txt
php readgroup.php <ISOGG_HapgrpJ.html >J.txt
php readgroup.php <ISOGG_HapgrpK.html >K.txt
php readgroup.php <ISOGG_HapgrpL.html >L.txt
php readgroup.php <ISOGG_HapgrpM.html >M.txt
php readgroup.php <ISOGG_HapgrpN.html >N.txt
php readgroup.php <ISOGG_HapgrpO.html >O.txt
php readgroup.php <ISOGG_HapgrpP.html >P.txt
php readgroup.php <ISOGG_HapgrpQ.html >Q.txt
php readgroup.php <ISOGG_HapgrpR.html >R.txt
php readgroup.php <ISOGG_HapgrpS.html >S.txt
php readgroup.php <ISOGG_HapgrpT.html >T.txt
php readindex.php <ISOGG_YDNA_SNP_Index.html >index.txt
